apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: customer-portal-namespace
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
